import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Layout/header";
import SideBar from "./components/Layout/sidebar";
import BaseLayout from "./components/Layout/baseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <BaseLayout>{children}</BaseLayout>
            </body>
        </html>
    );
}
