import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <div className="flex">
                    <div className="w-1/8 h-screen pl-2 pr-2 bg-gray-100">
                        Sidebar here
                    </div>
                    <div className="flex-1 pl-2">{children}</div>
                </div>
            </body>
        </html>
    );
}
